# Copyright 2025 thestill.ai
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Facts models for transcript cleaning.

Two-level facts architecture:
- PodcastFacts: Recurring knowledge (hosts, sponsors, keywords) - stable, user-editable
- EpisodeFacts: Episode-specific knowledge (guests, speaker mapping, topics)
"""

from typing import Dict, List

from pydantic import BaseModel, Field


class PodcastFacts(BaseModel):
    """
    Podcast-level facts that apply across all episodes.

    These facts are stable and only grow via user edits (no automatic accumulation).
    Stored as human-editable Markdown in data/podcast_facts/{slug}.facts.md
    """

    podcast_title: str
    hosts: List[str] = Field(default_factory=list)  # "Name - Description"
    recurring_roles: List[str] = Field(default_factory=list)  # "Ad Narrator - Reads sponsor segments"
    production_team: List[str] = Field(default_factory=list)  # "Dashiell Lewin - Research", "Becca Kinsel - Producer"
    known_guests: List[str] = Field(default_factory=list)  # "Name - Description"
    sponsors: List[str] = Field(default_factory=list)  # Sponsor/advertiser names
    keywords: List[str] = Field(default_factory=list)  # "Term (note about mishearing)"
    style_notes: List[str] = Field(default_factory=list)  # "British English preferred"


class EpisodeFacts(BaseModel):
    """
    Episode-specific facts extracted during Pass 1.

    Includes speaker mapping hypothesis generated by analyzing the transcript.
    Stored as Markdown in data/episode_facts/{podcast_slug}/{episode_slug}.facts.md
    """

    episode_title: str
    speaker_mapping: Dict[str, str] = Field(default_factory=dict)  # "SPEAKER_01": "Scott Galloway (Host)"
    guests: List[str] = Field(default_factory=list)  # "Name - Role/Description"
    topics_keywords: List[str] = Field(default_factory=list)  # Episode-specific topics
    ad_sponsors: List[str] = Field(default_factory=list)  # Sponsors mentioned in this episode
